### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by ZixuWang** [Xiaoyu006/MATP-with-HEAT#6]
could you please show how does the input data(the data after processing) look like?

**Comment by STing27** [comment]
Hi， I'm so sorry to bother you, this is fantastic work. But I'm stuck in reproducing the repo, can you help me?
What is the version of the inter dataset used by this warehouse? Is it the latest v1.2 or the old v1.1?
If it is the old v1.1, because the official has not provided it? Can you please share it with me?
